{
 "title": "App",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "/ response count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "irate(http_request_duration_seconds_count{route=\"/\"}[30s])"
    }
   ]
  },
  {
   "title": "Hits / Misses per Sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(redis_keyspace_hits_total{}[30s])",
     "legendFormat": "hits, {{ instance }}"
    },
    {
     "expr": "irate(redis_keyspace_misses_total{}[30s])",
     "legendFormat": "misses, {{ instance }}"
    }
   ]
  },
  {
   "title": "/ response time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_sum{route=\"/\"}[30s]) / increase(http_request_duration_seconds_count{route=\"/\"}[30s])"
    }
   ]
  },
  {
   "title": "Server load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "load 1" }
   ]
  }
 ]
}