global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'app'
    static_configs:
      - targets: [ 'nginx:80' ]
        labels:
          application: 'app'

  - job_name: 'php-exporter'
    static_configs:
      - targets: [ 'php-exporter:9253' ]
        labels:
          namespace: 'app'
          kubernetes_pod_name: 'app'

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: [ 'nginx-exporter:9113' ]

  - job_name: 'redis-exporter'
    static_configs:
      - targets: [ 'redis-exporter:9121' ]

  - job_name: 'aws-health-exporter'
    scrape_interval: 60s
    scrape_timeout: 40s
    static_configs:
      - targets: [ 'aws-health-exporter:9383' ]

  - job_name: 'domains-exporter'
    static_configs:
      - targets: [ 'domains-exporter:9203' ]

  - job_name: 'node-exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]

